version: '3'

services:
  frontend:
    image: os01glados/frontend
    build:
      context: .
      dockerfile: ./blog-frontend-vue/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  
  backend:
    image: os01glados/backend
    build: 
      context: .
      dockerfile: ./docker-backend/Dockerfile
    env_file:
      - ./docker-backend/.env
    ports:
      - "8000:8000"
    command: /usr/local/bin/gunicorn DjangoBlogTutorial.wsgi:application -b :8000