[tool.black]
line-length = 79
skip-string-normalization = true

[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning"
norecursedirs = "integration_tests"

DJANGO_SETTINGS_MODULE = "DjangoBlogTutorial.settings"

python_files = "tests.py test_*.py"

addopts = "-v --nomigrations  --cov=. --cov-report=html"