version: '3'

services:
  frontend:
    restart: always
    build:
      context: .
      dockerfile: ./blog-frontend-vue/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
  
  backend:
    restart: always
    build: 
      context: .
      dockerfile: ./docker-backend/Dockerfile
    volumes:
      - ./docker-backend:/code
    env_file:
      - ./docker-backend/.env
    ports:
      - "8000:8000"
    command: /usr/local/bin/gunicorn DjangoBlogTutorial.wsgi:application -b :8000