# Generated by Django 3.2.8 on 2022-02-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postpicture_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpicture',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
