# Generated by Django 3.2.8 on 2022-02-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_postpicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpicture',
            name='image_number',
            field=models.IntegerField(default=1),
        ),
    ]
