# Generated by Django 3.2.8 on 2022-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpicture',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
