# Generated by Django 3.2.8 on 2022-03-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_postpicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(
                default='https://os01glados-django-blog-statics.s3.amazonaws.com/default.jpg',
                max_length=500,
            ),
        ),
    ]
