# Generated by Django 3.2.8 on 2022-03-30 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAudio',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('audio', models.CharField(max_length=500, null=True)),
                ('audio_number', models.IntegerField(default=1)),
                (
                    'post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audios',
                        to='api.post',
                    ),
                ),
            ],
        ),
    ]
