# Generated by Django 3.2.8 on 2022-03-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_postaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaudio',
            name='audio_name',
            field=models.CharField(default='unknown', max_length=500),
        ),
    ]
