# Generated by Django 3.2.8 on 2022-04-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_unused_tables'),
    ]

    operations = []
