# Generated by Django 3.2.8 on 2022-04-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_unused_tables'),
    ]

    operations = [
        migrations.RunSQL('drop table if exists public.users_profile cascade')
    ]
